version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - run: python -m venv .venv
      - run: . .venv/bin/activate && make deps
      - run: . .venv/bin/activate && make test

workflows:
  basic:
    jobs:
      - build-and-test
